[build]
  publish = "."  # Diretório raiz do seu projeto
  command = "npm run build"  # Comando para build, se você tiver algum (opcional)
  functions = "netlify/functions"  # Funções serverless, se você usar

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
